# Netlify configuration for Next.js App Router
site_id = "d61cfc89-3a4c-4143-b349-f318fb313c6d"

[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache static Next assets aggressively
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
