import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/SiteHeader";
import { AnalyticsInit } from "@/components/AnalyticsInit";
import { AuthProvider } from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-50 text-neutral-900`}
      >
        <AuthProvider>
          <SiteHeader />
          <AnalyticsInit />
          <main className="min-h-screen">{children}</main>
          <footer className="border-t border-neutral-200 mt-24 py-8 text-center text-sm text-neutral-500">
            © {new Date().getFullYear()} My Blog.
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
